# Lab | Numpy Deep Dive

### 1. Import the NUMPY package under the name np.


In [1]:
### [your code here]
import numpy as np





### 2. Print the NUMPY version and the configuration.


In [2]:
### [your code here]
print(np.__version__)
np.show_config()


2.2.5
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-065080rt/cp313-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/include
    lib directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-065080rt/cp313-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.28  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Haswell MAX_THREADS=24
    pc file directory: D:/a/numpy/numpy/.openblas
    version: 0.3.28
  lapack:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-065080rt/cp313-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/include
    lib directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-065080rt/cp313-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.

### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?


In [13]:
### [your code here]
# Method 1: Using np.random.rand
a = np.random.rand(2, 3, 5)
#print("random.rand:", a)

# Method 2: Using np.random.random_sample
a = np.random.random_sample((2, 3, 5))
#print("random_sample:", a)

# Method 3: Using np.random.uniform
a = np.random.uniform(0, 1, (2, 3, 5))
#print("random.uniform:", a)

# Method 4: Using np.random.randn (standard normal distribution)
a = np.random.randn(2, 3, 5)
#print("random.randn:", a)

# Method 5: Using np.random.randint (random integers, scaled to floats)
a = np.random.randint(0, 100, (2, 3, 5)) / 100.0
print("random.randint:", a)

# Method 6: Using np.empty and filling it with random values
a = np.empty((2, 3, 5))
a[:] = np.random.rand(2, 3, 5)
#print("random.rand with empty variable:", a)


random.randint: [[[0.17 0.22 0.25 0.94 0.46]
  [0.67 0.81 0.86 0.57 0.38]
  [0.44 0.53 0.82 0.02 0.13]]

 [[0.18 0.63 0.52 0.72 0.13]
  [0.66 0.22 0.72 0.55 0.08]
  [0.89 0.14 0.83 0.24 0.15]]]



### 4. Print a.


In [11]:
### [your code here]
print(a)


[[[0.21655809 0.06640551 0.84166532 0.99322523 0.97437033]
  [0.73401661 0.77438803 0.41836324 0.53243085 0.2531631 ]
  [0.18287475 0.09424083 0.83053862 0.37454524 0.82985794]]

 [[0.70794959 0.01956831 0.91897163 0.31193413 0.27576659]
  [0.04376403 0.48390919 0.21771284 0.89421278 0.12088888]
  [0.10569049 0.18105116 0.22735079 0.26585621 0.33871129]]]


### 5. Create a 5x2x3 3-dimensional array with all values equaling 1.
### Assign the array to variable "b"


In [19]:
### [your code here]
b = np.ones((5, 2, 3))



### 6. Print b.


In [20]:
### [your code here]
print(b)


[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]



### 7. Do a and b have the same size? How do you prove that in Python code?


In [27]:
### [your code here]
if a.size == b.size:
    print("a and b have the same size")
    
else:
    print("a and b have different sizes")

print(a.size, b.size)


a and b have the same size
30 30



### 8. Are you able to add a and b? Why or why not?


In [34]:
### [your code here]
"""No we are not able to add 'a' and 'b' because they have different shapes. 
As per the broadcasting rules in numpy, the shapes of the arrays must be compatible which means they should be same or one of them should be 1
For our code:
a.shape = (2, 3, 5)
b.shape = (5, 2, 3)

The dimensions don't align in a way that would allow broadcasting:

The first dimension of a is 2, while the first dimension of b is 5.
The second dimension of a is 3, and the second dimension of b is 2.
The third dimension of a is 5, and the third dimension of b is 3. 

As per the broadcasting rules in numpy, the shapes of the arrays must be compatible which means they should be same or one of them should be 1
As any of these conditions are not met, we canno add 'a and 'b'."""


"No we are not able to add 'a' and 'b' because they have different shapes. \nAs per the broadcasting rules in numpy, the shapes of the arrays must be compatible which means they should be same or one of them should be 1\nFor our code:\na.shape = (2, 3, 5)\nb.shape = (5, 2, 3)\n\nThe dimensions don't align in a way that would allow broadcasting:\n\nThe first dimension of a is 2, while the first dimension of b is 5.\nThe second dimension of a is 3, and the second dimension of b is 2.\nThe third dimension of a is 5, and the third dimension of b is 3. \n\nAs per the broadcasting rules in numpy, the shapes of the arrays must be compatible which means they should be same or one of them should be 1\nAs any of these conditions are not met, we canno add 'a and 'b'."



### 9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".


In [30]:
### [your code here]
c = b.transpose((1, 2, 0))
print(c.shape)



(2, 3, 5)



### 10. Try to add a and c. Now it should work. Assign the sum to variable "d". But why does it work now?


In [33]:
### [your code here]
d = a + c
print(d.shape)
print (d)

"""it worked because the shapes of 'a' and 'c' are now compatible for boradcasting"""



(2, 3, 5)
[[[1.25981827 1.39519379 1.44234385 1.46874158 1.50662712]
  [1.78968524 1.82254671 1.26932618 1.44304531 1.28013578]
  [1.86482855 1.17317569 1.71204915 1.72204516 1.10928244]]

 [[1.05756323 1.32015538 1.05633544 1.99087328 1.68776029]
  [1.39820198 1.02154498 1.32971737 1.04505438 1.04143463]
  [1.85357474 1.57423069 1.96255241 1.84238581 1.41077028]]]


"it worked because the shapes of 'a' and 'c' are now compatible for boradcasting"


### 11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.


In [36]:
### [your code here]
print("array of a:", a)
print("array of d:", d)

"""Both 'a' and 'd' are of same shape but the values are different because 'a' is a random array and 'd' is the sum of  'a' and transposed 'b'"""



array of a: [[[0.25981827 0.39519379 0.44234385 0.46874158 0.50662712]
  [0.78968524 0.82254671 0.26932618 0.44304531 0.28013578]
  [0.86482855 0.17317569 0.71204915 0.72204516 0.10928244]]

 [[0.05756323 0.32015538 0.05633544 0.99087328 0.68776029]
  [0.39820198 0.02154498 0.32971737 0.04505438 0.04143463]
  [0.85357474 0.57423069 0.96255241 0.84238581 0.41077028]]]
array of d: [[[1.25981827 1.39519379 1.44234385 1.46874158 1.50662712]
  [1.78968524 1.82254671 1.26932618 1.44304531 1.28013578]
  [1.86482855 1.17317569 1.71204915 1.72204516 1.10928244]]

 [[1.05756323 1.32015538 1.05633544 1.99087328 1.68776029]
  [1.39820198 1.02154498 1.32971737 1.04505438 1.04143463]
  [1.85357474 1.57423069 1.96255241 1.84238581 1.41077028]]]


"Both 'a' and 'd' are of same shape but the values are different because 'a' is a random array and 'd' is the sum of  'a' and transposed 'b'"


### 12. Multiply a and c. Assign the result to e.


In [37]:
### [your code here]
e = a*c
print(e.shape)
print (e)


(2, 3, 5)
[[[0.25981827 0.39519379 0.44234385 0.46874158 0.50662712]
  [0.78968524 0.82254671 0.26932618 0.44304531 0.28013578]
  [0.86482855 0.17317569 0.71204915 0.72204516 0.10928244]]

 [[0.05756323 0.32015538 0.05633544 0.99087328 0.68776029]
  [0.39820198 0.02154498 0.32971737 0.04505438 0.04143463]
  [0.85357474 0.57423069 0.96255241 0.84238581 0.41077028]]]




### 13. Does e equal to a? Why or why not?


In [38]:
### [your code here]


"""Both 'a' and 'e' are of same shape but the values are different because 'a' is a random array and 'e' is the multiple of  'a' and transposed 'b'"""

"Both 'a' and 'e' are of same shape but the values are different because 'a' is a random array and 'e' is the multiple of  'a' and transposed 'b'"



### 14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"


In [40]:
### [your code here]

d_max = d.max()
d_min = d.min()
d_mean = d.mean()
print("MAX Value of d:", d_max)
print("MIN Value of d:", d_min)
print("MEAN Value of d:", d_mean)




MAX Value of d: 1.9908732764427755
MIN Value of d: 1.021544975378919
MEAN Value of d: 1.4616999904127739



### 15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.


In [41]:
### [your code here]
f = np.empty((2,3,5))





### 16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.



In [43]:
### [your code here]
for i in range(d.shape[0]):
    for j in range(d.shape[1]):
        for k in range(d.shape[2]):
            if d[i][j][k] == d_max:
                f[i][j][k] = 100
            elif d[i][j][k] == d_min:
                f[i][j][k] = 0
            elif d[i][j][k] == d_mean:
                f[i][j][k] = 50
            elif (d[i][j][k] > d_mean) & (d[i][j][k] < d_max):
                f[i][j][k] = 75
            elif (d[i][j][k] > d_min) & (d[i][j][k] < d_mean):
                f[i][j][k] = 25
print(f)


[[[ 25.  25.  25.  75.  75.]
  [ 75.  75.  25.  25.  25.]
  [ 75.  25.  75.  75.  25.]]

 [[ 25.  25.  25. 100.  75.]
  [ 25.   0.  25.  25.  25.]
  [ 75.  75.  75.  75.  25.]]]






### 17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])



In [45]:
### [your code here]
print("d array:","\n", d)
print("f array:", "\n", f)

d array: 
 [[[1.25981827 1.39519379 1.44234385 1.46874158 1.50662712]
  [1.78968524 1.82254671 1.26932618 1.44304531 1.28013578]
  [1.86482855 1.17317569 1.71204915 1.72204516 1.10928244]]

 [[1.05756323 1.32015538 1.05633544 1.99087328 1.68776029]
  [1.39820198 1.02154498 1.32971737 1.04505438 1.04143463]
  [1.85357474 1.57423069 1.96255241 1.84238581 1.41077028]]]
f array: 
 [[[ 25.  25.  25.  75.  75.]
  [ 75.  75.  25.  25.  25.]
  [ 75.  25.  75.  75.  25.]]

 [[ 25.  25.  25. 100.  75.]
  [ 25.   0.  25.  25.  25.]
  [ 75.  75.  75.  75.  25.]]]


### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.

In [47]:

flat = [string_value for alphabet in d for row in alphabet for string_value in row]
d_min = min(flat)
d_max = max(flat)
d_mean = sum(flat) / len(flat)

# Create a new 3D list f of the same shape
f = []

for i in range(len(d)):
    alphabet = []
    for j in range(len(d[i])):
        row = []
        for k in range(len(d[i][j])):
            val = d[i][j][k]
            if val == d_max:
                row.append('A')
            elif val == d_min:
                row.append('B')
            elif val == d_mean:
                row.append('C')
            elif d_mean < val < d_max:
                row.append('D')
            elif d_min < val < d_mean:
                row.append('E')
        alphabet.append(row)
    f.append(alphabet)

# Output the result
print("Original 3D list (d):")
for alphabet in d:
    print(alphabet)

print("\nLetter-coded 3D list (f):")
for alphabet in f:
    print(alphabet)


Original 3D list (d):
[[1.25981827 1.39519379 1.44234385 1.46874158 1.50662712]
 [1.78968524 1.82254671 1.26932618 1.44304531 1.28013578]
 [1.86482855 1.17317569 1.71204915 1.72204516 1.10928244]]
[[1.05756323 1.32015538 1.05633544 1.99087328 1.68776029]
 [1.39820198 1.02154498 1.32971737 1.04505438 1.04143463]
 [1.85357474 1.57423069 1.96255241 1.84238581 1.41077028]]

Letter-coded 3D list (f):
[['E', 'E', 'E', 'D', 'D'], ['D', 'D', 'E', 'E', 'E'], ['D', 'E', 'D', 'D', 'E']]
[['E', 'E', 'E', 'A', 'D'], ['E', 'B', 'E', 'E', 'E'], ['D', 'D', 'D', 'D', 'E']]
